name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*
      - uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: olafurpg/setup-scala@v12
      - name: Checking your code format
        run: sbt scalafmtCheckAll scalafmtSbtCheck
      - name: Run tests
        run: |
          sbt +test
      - name: Run documentation
        run: |
          sbt packageSrc docs/mdoc
